### ISSUE TITLE
运行python apex.py后就一直这样

### ISSUE THREAD

**Issue by blraksd** [EthanH3514/AL_Yolo#14]
![AF}Z$}BBTQOPKOTRJ@QPLD4](https://github.com/EthanH3514/AL_Yolo/assets/142481082/90be55bf-d742-4323-9d60-7a9c64d7888c)

**Comment by EthanH3514** [comment]
需要等到有提示声音响起后按下 `home` 键启动，提示声音响起前为初始化阶段

**Comment by blraksd** [comment]
![F$@LTJG Y51XCH@ C4H5YN7](https://github.com/EthanH3514/AL_Yolo/assets/142481082/e086aefa-4987-460e-9a7f-accd86918292)
运行后一旦切到其它窗口就会报错

> 需要等到有提示声音响起后按下 `home` 键启动，提示声音响起前为初始化阶段

**Comment by blraksd** [comment]
补充一下，是yolov5捕捉到模型后产生的错误，可能是torchvision::nms运算符无法使用来自CUDA后端的参数运行。该运算符不是在此后端不存在就是在选择性/自定义构建过程中被省略

> ![F$@LTJG Y51XCH@ C4H5YN7](https://user-images.githubusercontent.com/142481082/261342445-e086aefa-4987-460e-9a7f-accd86918292.png) 运行后一旦切到其它窗口就会报错
> 
> > 需要等到有提示声音响起后按下 `home` 键启动，提示声音响起前为初始化阶段

**Comment by blraksd** [comment]
下载官网的13.0版本后解决了，但切进游戏后会有新问题
`Traceback (most recent call last):
  File "E:\AL_Yolo-master\dxcam\core\duplicator.py", line 26, in update_frame
_ctypes.COMError: (-2005270490, '键控互斥已弃用。', (None, None, None, 0, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\AL_Yolo-master\dxcam\dxcam.py", line 220, in __capture
  File "E:\AL_Yolo-master\dxcam\dxcam.py", line 112, in _grab
  File "E:\AL_Yolo-master\dxcam\core\duplicator.py", line 35, in update_frame
  File "E:\AL_Yolo-master\dxcam\core\duplicator.py", line 20, in __post_init__
AttributeError: 'NoneType' object has no attribute 'output'

Exception in thread DXCamera:
Traceback (most recent call last):
  File "F:\python\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "F:\python\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "E:\AL_Yolo-master\dxcam\dxcam.py", line 252, in __capture
  File "E:\AL_Yolo-master\dxcam\dxcam.py", line 186, in stop
  File "F:\python\lib\threading.py", line 1086, in join
    raise RuntimeError("cannot join current thread")
RuntimeError: cannot join current thread
[-41.28, 7.4399999999999995]`

**Comment by EthanH3514** [comment]
发现你的错误报告中有 `dxcam` 的文件夹以及文件，是否是代码未更新导致的？

我之前用的dxcam实现的高速截图，后来因为dxcam停止维护了就换成了dxshot，试试重新clone代码再运行程序

**Comment by blraksd** [comment]
重下了一遍项目，还是原来一样的问题

> 发现你的错误报告中有 `dxcam` 的文件夹以及文件，是否是代码未更新导致的？
> 
> 我之前用的dxcam实现的高速截图，后来因为dxcam停止维护了就换成了dxshot，试试重新clone代码再运行程序

**Comment by DontWantToName** [comment]
> 下载官网的13.0版本后解决了，但切进游戏后会有新问题 'Traceback（最近一次调用）： 文件 “E：\AL_Yolo-master\dxcam\core\duplicator.py”，第 26 行，update_frame _ctypes。COMError： （-2005270490， '键控互斥已弃用。'， （无， 无， 无， 0， 无））
> 
> 在处理上述异常期间，发生了另一个异常：
> 
> 回溯（最近一次调用）：文件 “E：\AL_Yolo-master\dxcam\dxcam.py”，第 220 行，位于__capture文件 “E：\AL_Yolo-master\dxcam\dxcam.py”，第 112 行，在_grab文件 “E：\AL_Yolo-master\dxcam\core\duplicator.py”，第 35 行，在update_frame **post_init**中的文件 “E：\AL_Yolo-master\dxcam\core\duplicator.py”，第 20 行 属性错误：“NoneType”对象没有属性“输出”
> 
> 线程 DXCamera 中的异常：回溯（最近一次调用）：文件 “F：\python\lib\threading.py”，第 1009 行，在 self.run（） 文件中 _bootstrap_inner 文件 “F：\python\lib\threading.py”，第 946 行，在运行中 self._target（*self._args， **self._kwargs） 文件 “E：\AL_Yolo-master\dxcam\dxcam.py”，第 252 行，在__capture文件 “E：\AL_Yolo-master\dxcam\dxcam.py”中，第 186 行，在停止文件中 文件 “F：\python\lib\threading.py“，第 1086 行，在连接引发中 运行时错误（”无法加入当前线程“） 运行时错误：无法加入当前线程 [-41.28， 7.4399999999999995]'

我也是这个问题

**Comment by N1ckeyQu** [comment]
> 需要等到有提示声音响起后按下 `home` 键启动，提示声音响起前为初始化阶段

我按照reademe上的步骤一步步走下来，运行apex.py并未听到所谓的提示声音

> 发现你的错误报告中有 dxcam 的文件夹以及文件，是否是代码未更新导致的？
我之前用的dxcam实现的高速截图，后来因为dxcam停止维护了就换成了dxshot，试试重新clone代码再运行程序

我本地clone的是最新代码，你说你换成dxshot，你确定你的最新代码已经提交了吗

**Comment by N1ckeyQu** [comment]
> 下载官网的13.0版本后解决了，但切进游戏后会有新问题 `Traceback (most recent call last): File "E:\AL_Yolo-master\dxcam\core\duplicator.py", line 26, in update_frame _ctypes.COMError: (-2005270490, '键控互斥已弃用。', (None, None, None, 0, None))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "E:\AL_Yolo-master\dxcam\dxcam.py", line 220, in __capture File "E:\AL_Yolo-master\dxcam\dxcam.py", line 112, in _grab File "E:\AL_Yolo-master\dxcam\core\duplicator.py", line 35, in update_frame File "E:\AL_Yolo-master\dxcam\core\duplicator.py", line 20, in **post_init** AttributeError: 'NoneType' object has no attribute 'output'
> 
> Exception in thread DXCamera: Traceback (most recent call last): File "F:\python\lib\threading.py", line 1009, in _bootstrap_inner self.run() File "F:\python\lib\threading.py", line 946, in run self._target(*self._args, **self._kwargs) File "E:\AL_Yolo-master\dxcam\dxcam.py", line 252, in __capture File "E:\AL_Yolo-master\dxcam\dxcam.py", line 186, in stop File "F:\python\lib\threading.py", line 1086, in join raise RuntimeError("cannot join current thread") RuntimeError: cannot join current thread [-41.28, 7.4399999999999995]`

我和你遇到的问题完全一致

**Comment by EthanH3514** [comment]
> > 需要等到有提示声音响起后按下 `home` 键启动，提示声音响起前为初始化阶段
> 
> 我按照reademe上的步骤一步步走下来，运行apex.py并未听到所谓的提示声音
> 
> > 发现你的错误报告中有 dxcam 的文件夹以及文件，是否是代码未更新导致的？
> > 我之前用的dxcam实现的高速截图，后来因为dxcam停止维护了就换成了dxshot，试试重新clone代码再运行程序
> 
> 我本地clone的是最新代码，你说你换成dxshot，你确定你的最新代码已经提交了吗

没有提示音是因为在后续的更新中把这个取消掉了

最新代码提交了，如果有dxcam的报错可能因为dxshot是在dxcam上实现的

**Comment by liushizhong** [comment]
我也出现了上述的问题。我发现只要切屏就会发生，所以我把游戏窗口化后就没有报错了。但是不知道为什么一直没看到推理出来的框，然后游戏更新后（2024.4.4）好像不能用了，我打开后反作弊系统把我踢下线了
