### ISSUE TITLE
'DXCamera' object has no attribute 'is_capturing'

### ISSUE THREAD

**Issue by wulidede** [EthanH3514/AL_Yolo#36]
当我运行apex.py之后，会弹出用户界面，点击“开启目标检测”之后，会出现错误信息如下：
`目标检测已开启
'gbk' codec can't decode byte 0xff in position 0: illegal multibyte sequence
YOLOv5  v1.0-1-g0844685 Python-3.11.5 torch-2.0.1 CUDA:0 (NVIDIA GeForce RTX 4070 Laptop GPU, 8188MiB)

Fusing layers... 
Model summary: 157 layers, 7015519 parameters, 0 gradients
Exception in thread Thread-2 (work):
Traceback (most recent call last):
  File "D:\software\Anaconda3\envs\gym\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "D:\software\Anaconda3\envs\gym\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\zhanghd\Desktop\download\AL_Yolo\detect.py", line 149, in work
    self.run()
  File "C:\Users\zhanghd\Desktop\download\AL_Yolo\detect.py", line 92, in run
    dataset = LoadScreen()
              ^^^^^^^^^^^^
  File "C:\Users\zhanghd\Desktop\download\AL_Yolo\Capture.py", line 19, in __init__
    self.camera = dxshot.create(region=self.region, output_color="RGB")
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zhanghd\Desktop\download\AL_Yolo\dxshot.py", line 112, in create
  File "C:\Users\zhanghd\Desktop\download\AL_Yolo\dxshot.py", line 71, in create
  File "C:\Users\zhanghd\Desktop\download\AL_Yolo\dxcam\dxcam.py", line 51, in __init__
  File "C:\Users\zhanghd\Desktop\download\AL_Yolo\dxcam\dxcam.py", line 294, in _validate_region
ValueError: Invalid Region: Region should be in 1707x1067
Exception ignored in: <compiled_function DXCamera.__del__ at 0x000001EA91972840>
Traceback (most recent call last):
  File "C:\Users\zhanghd\Desktop\download\AL_Yolo\dxcam\dxcam.py", line 310, in __del__
  File "C:\Users\zhanghd\Desktop\download\AL_Yolo\dxcam\dxcam.py", line 305, in release
  File "C:\Users\zhanghd\Desktop\download\AL_Yolo\dxcam\dxcam.py", line 199, in stop
AttributeError: 'DXCamera' object has no attribute 'is_capturing'`
我使用的是python3.11对应的dxshot，请问该错误是如何引起的？

**Comment by EthanH3514** [comment]
貌似问题出在 `dxcam` 这个库里，这个库是我用来给屏幕截屏的一个库，我本地无法复现这个问题

以下是我的建议：
* 将python版本换成 3.10.x
* 在[dxcam](https://github.com/ra1nty/DXcam)这个仓库的issue中找到[相同的问题](https://github.com/ra1nty/DXcam/issues?q=%27DXCamera%27+object+has+no+attribute+%27is_capturing%27)可以参考

**Comment by dclemon** [comment]
> 当我运行apex.py之后，会弹出用户界面，点击“开启目标检测”之后，会出现错误信息如下： `目标检测已开启 'gbk' codec can't decode byte 0xff in position 0: illegal multibyte sequence YOLOv5 v1.0-1-g0844685 Python-3.11.5 torch-2.0.1 CUDA:0 (NVIDIA GeForce RTX 4070 Laptop GPU, 8188MiB)
> 
> Fusing layers... Model summary: 157 layers, 7015519 parameters, 0 gradients Exception in thread Thread-2 (work): Traceback (most recent call last): File "D:\software\Anaconda3\envs\gym\Lib\threading.py", line 1038, in _bootstrap_inner self.run() File "D:\software\Anaconda3\envs\gym\Lib\threading.py", line 975, in run self._target(*self._args, **self._kwargs) File "C:\Users\zhanghd\Desktop\download\AL_Yolo\detect.py", line 149, in work self.run() File "C:\Users\zhanghd\Desktop\download\AL_Yolo\detect.py", line 92, in run dataset = LoadScreen() ^^^^^^^^^^^^ File "C:\Users\zhanghd\Desktop\download\AL_Yolo\Capture.py", line 19, in **init** self.camera = dxshot.create(region=self.region, output_color="RGB") ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\zhanghd\Desktop\download\AL_Yolo\dxshot.py", line 112, in create File "C:\Users\zhanghd\Desktop\download\AL_Yolo\dxshot.py", line 71, in create File "C:\Users\zhanghd\Desktop\download\AL_Yolo\dxcam\dxcam.py", line 51, in **init** File "C:\Users\zhanghd\Desktop\download\AL_Yolo\dxcam\dxcam.py", line 294, in _validate_region ValueError: Invalid Region: Region should be in 1707x1067 Exception ignored in: <compiled_function DXCamera.**del** at 0x000001EA91972840> Traceback (most recent call last): File "C:\Users\zhanghd\Desktop\download\AL_Yolo\dxcam\dxcam.py", line 310, in **del** File "C:\Users\zhanghd\Desktop\download\AL_Yolo\dxcam\dxcam.py", line 305, in release File "C:\Users\zhanghd\Desktop\download\AL_Yolo\dxcam\dxcam.py", line 199, in stop AttributeError: 'DXCamera' object has no attribute 'is_capturing'` 我使用的是python3.11对应的dxshot，请问该错误是如何引起的？

我也遇到同样的问题，我用的是带核显的笔记本，显卡3050ti，选择python运行显卡为核显时没有此报错，目前不知道原因

**Comment by narugakuru** [comment]
我在运行apex.py也遇到了这个问题，python版本是3.10.14，cuda11.8，值得一提的是numpys的1.26.3会发生依赖冲突，改成了1.26.4
'gbk' codec can't decode byte 0xff in position 0: illegal multibyte sequence
YOLOv5  v1.0-4-gf93c982 Python-3.10.14 torch-2.0.1+cu118 CUDA:0 (NVIDIA GeForce RTX 4060 Laptop GPU, 8188MiB)

Exception in thread Thread-4 (work):
Traceback (most recent call last):
  File "E:\Environment\anaconda3\envs\apex_v5\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "E:\Environment\anaconda3\envs\apex_v5\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "E:\Code\Yolo\AL_Yolo\detect.py", line 168, in work
    self.run()
  File "E:\Code\Yolo\AL_Yolo\detect.py", line 95, in run
    dataset = LoadScreen()
  File "E:\Code\Yolo\AL_Yolo\Capture.py", line 17, in __init__
    self.camera = dxshot.create(region=self.region, output_color="RGB")
  File "E:\Code\Yolo\AL_Yolo\dxshot.py", line 112, in create
  File "E:\Code\Yolo\AL_Yolo\dxshot.py", line 71, in create
  File "E:\Code\Yolo\AL_Yolo\dxcam\dxcam.py", line 51, in __init__
  File "E:\Code\Yolo\AL_Yolo\dxcam\dxcam.py", line 294, in _validate_region
ValueError: Invalid Region: Region should be in 1707x960
Exception ignored in: <compiled_function DXCamera.__del__ at 0x000002A46A5E0130>
Traceback (most recent call last):
  File "E:\Code\Yolo\AL_Yolo\dxcam\dxcam.py", line 310, in __del__
  File "E:\Code\Yolo\AL_Yolo\dxcam\dxcam.py", line 305, in release
  File "E:\Code\Yolo\AL_Yolo\dxcam\dxcam.py", line 199, in stop
AttributeError: 'DXCamera' object has no attribute 'is_capturing'

**Comment by dashuao** [comment]
我知道怎么解决 有偿

**Comment by dashuao** [comment]
需要解决联系 jeffxu0708@gmail.com 有偿

**Comment by dclemon** [comment]
哥们你掉钱眼里了吧这东西也要米？dxcam只有独显直连可以用，部分笔记本用不了解决方案其他issue里已经说过了图形设置里面把python设置CPU运行就行了

dashuao ***@***.***>于2024年5月6日 周一18:44写道：

**Comment by tuzibr** [comment]
我用笔记本分辨率缩放开到125就可以，开到150就会有这个报错
